# Release: https://github.com/iscander01/arbitrum-vibekit/releases/tag/v1.0.111
# Workflow URL: https://github.com/iscander01/arbitrum-vibekit/actions/runs/28100092348
# Commit: https://github.com/iscander01/arbitrum-vibekit/commit/777f63469af83e294532d20dc2b2f10efdf1db67
# Dockerfile Path: typescript/clients/web/Dockerfile
# Docker Compose Location: typescript/clients/web/docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/iscander01/arbitrum-vibekit@sha256:92bd6bec22d2d59f6bf1730c39374a8fc6e399dcd8f130ae6856f5b73b638780
    ports:
      - '3000:80'
